Pass actual format string instead of nullptr in Parser_oom_handler::handle_condition
Should the code path be actually exercised, memory errors were likely to have
occurred instead of diagnostics.

This fixes a GCC build error:

sql/sql_parse.cc:7909:17: error: too many arguments for format [-Werror=format-extra-args]
 7909 |                 static_cast<ulonglong>(thd->variables.parser_max_mem_size),

Squash with 67fcc60a43687c3e116c7f57e13b52732ad25231