Fix Google Test upgrade
Summary:
When I'm updating mysqldefs.sh I noticed latest Google Test introduces a new flag kSkip in TestPartResult::Type and that will introduce following build failure:

/home/yzha/mysql/mysql-fork2/unittest/gunit/tap_event_listener.cc:127:11: error: enumeration value 'kSkip' not handled in switch
      [-Werror,-Wswitch]
  switch (type)
          ^
1 error generated.
make[2]: *** [unittest/gunit2/CMakeFiles/gunit_small.dir/__/gunit/tap_event_listener.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....

The fix is to add a default statement so that compiler stops complaining.

NOTE: Obviously the right way is to add the missing kStep case. In theory I could fix this the right way separately with two fixes - one in mysql repo with the right fix, and the tools tp2 update. however, the CI in both diff would all fail, giving me little coverage. So I've decided to stage this work - first get this change in, allowing the tools CI to pass, and then get the tools CI fix in, and finally update this fix with a proper fix, in 3 stages.

Reviewed By: luqun

Differential Revision: D15886453

fbshipit-source-id: 8d0224e6674