Fix LLVM 18 compilation errors
- struct CHARSET_INFO: initialize all fields to zero, as memset is no longer
  valid on its variables since acquiring an std::atomic field
- my_charset_file_reset_charset: placement-new construct an new default object
  instead of memset'ing it to zero, fixing [1]
- strings/conf_to_src.cc: do not memset an object that is already
  default-initialized to zero, fixing [2]

Squash with 6637b51c7df3fb8e2c4994dd0358acb92f7ba017

[1]:

strings/ctype.cc: In function ‘void my_charset_file_reset_charset(MY_CHARSET_FILE*)’:
strings/ctype.cc:303:9: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct CHARSET_INFO’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
  303 |   memset(&i->cs, 0, sizeof(i->cs));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from strings/ctype.cc:36:
include/m_ctype.h:383:8: note: ‘struct CHARSET_INFO’ declared here
  383 | struct CHARSET_INFO {
      |        ^~~~~~~~~~~~

[2]:

strings/conf_to_src.cc: In function ‘int main(int, char**)’:
strings/conf_to_src.cc:292:9: error: ‘void* memset(void*, int, size_t)’ clearing an object of type ‘struct CHARSET_INFO’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
  292 |   memset(&ncs, 0, sizeof(ncs));
      |   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
In file included from strings/conf_to_src.cc:32:
include/m_ctype.h:383:8: note: ‘struct CHARSET_INFO’ declared here
  383 | struct CHARSET_INFO {
      |        ^~~~~~~~~~~~