Added --read-from-binlog-server option for mysqlbinlog due to special binlog server error code
Summary:
Binlog server will always send 1236 error code when it has completed sending all the binlogs from HDFS.

In the case of OLM and CRT, we use mysqlbinlog to replay binlogs from binlog server. However, olm relies on the mysqlbinlog's return code to determine if the replay is successful.

I have added --read-from-binlog-server option for mysqlbinlog so that mysqlbinlog can handle the special binlog server error code and error messages and return success for this.

Test Plan:
Not easy to write a MTR test since it needs binlog server.

Manually launch a binlog server on port 3351

  /mysqlbinlog --skip-gtids --skip-empty-trans --database=test --exclude-gtids=cd10b08a-1b7f-11e7-8b82-e51cd8e7fe41:1-2176000 --host=127.0.0.1 --port=3351 --user=admin3 --password=EWunsL@Li}ONAbF3 --to-last-log --print-gtids --read-from-remote-master=BINLOG-DUMP-GTIDS --read-from-binlog-server

  Server error code: 1236
  Sever error message: The binlog server has finished sending all available binlogs from the HDFS and has no more binlogs to send. Executed gtid set from binlog server: CD10B08A-1B7F-11E7-8B82-E51CD8E7FE41:1-2178489
  DELIMITER ;
  # End of log file
  ROLLBACK /* added by mysqlbinlog */;
  /*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
  /*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
  Executed gtids: cd10b08a-1b7f-11e7-8b82-e51cd8e7fe41:1-2178289:2178291-2178307:2178309-2178471:2178473-2178489

Without this option

  ./mysqlbinlog --skip-gtids --skip-empty-trans --database=test --exclude-gtids=cd10b08a-1b7f-11e7-8b82-e51cd8e7fe41:1-2176000 --host=127.0.0.1 --port=3351 --user=admin3 --password=EWunsL@Li}ONAbF3 --to-last-log --print-gtids --read-from-remote-master=BINLOG-DUMP-GTIDS

Error message:

  ERROR: Failed to read binary log 1491947688_1491948105_xdb0176.prn1_binary-logs-3308.000601.zst, error 1236
  DELIMITER ;
  # End of log file
  ROLLBACK /* added by mysqlbinlog */;
  /*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
  /*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
  Executed gtids: cd10b08a-1b7f-11e7-8b82-e51cd8e7fe41:1-2178289:2178291-2178307:2178309-2178471:2178473-2178489

Other test:

  tengli@devbig569:~/mysql/5.6/_build-5.6-Debug/client$ ./mysqlbinlog --skip-gtids --skip-empty-trans --database=tengli_test --exclude-gtids=cd10b08a-1b7f-11e7-8b82-e51cd8e7fe41:1-2133000 --host=127.0.0.1 --port=3351 --user=admin3 --password=EWunsL@Li}ONAbF3 --to-last-log --print-gtids --read-from-binlog-server
  ERROR: --opt-read-from-binlog-server requires --read-from-remote-master=BINLOG-DUMP-GTIDS option

Reviewers: abhinavsharma

Reviewed By: abhinavsharma

Subscribers: junyilu, webscalesql-eng@fb.com, #mysql_infra, flupps, divij

Differential Revision: https://phabricator.intern.facebook.com/D4866487

Tasks: 13157916

Signature: t1:4866487:1491933483:098f0de0b946684c9ab8154db068ac7d2a826955