Fix MyRocks code to work with the latest RocksDB from `master`
Summary: https://github.com/facebook/rocksdb/commit/f7bb1a0060cfaeefefac9a32734956653ea7e35c has made `Add` function deprecated. Adjust our code to deal with this till we update to the latest version of RocksDB.

Test Plan:
  - Before the fix the following compilation error will occur: "`storage/rocksdb/rdb_sst_info.cc:100:43: error: ‘rocksdb::Status rocksdb::SstFileWriter::Add(const rocksdb::Slice&, const rocksdb::Slice&)’ is deprecated`".
  - After the fix latest MyRocks and latest RocksDB compile cleanly.

Reviewers: mung, herman

Reviewed By: herman

Subscribers: webscalesql-eng@fb.com

Differential Revision: https://phabricator.intern.facebook.com/D5148110

Signature: t1:5148110:1496166420:efe20bd32dbf3284b84c7c2d3ff332c04c16361e