Fix mysqldump macOS build regression
Use the standard macro to fprintf a uint64_t value. This fixes
client/mysqldump.cc:6347:11: error: format specifies type 'unsigned long' but the argument has type 'unsigned long long' [-Werror,-Wformat]
          itr->second);
          ^~~~~~~~~~~

Squash with fb8bf5e253e8ccaf7abf9094f50ef80f74c60ae3