PS-7032: fix compilation errors when libstdc++-10 is installed
This patch fixes only errors (warning are left intact) with the newest libstdc++-10 installed along with gcc-10.
The errors are triggered also when using older compilers that started to use the libstdc++-10.

The list of errors:
1.
```
In file included from /usr/include/c++/10/memory:83,
                 from /data/mysql-server/fb-5.6.35/sql/sql_class.h:26,
                 from /data/mysql-server/fb-5.6.35/storage/archive/ha_archive.cc:21:
/usr/include/c++/10/bits/unique_ptr.h: In instantiation of ‘constexpr std::unique_ptr<_Tp, _Dp>::unique_ptr(std::nullptr_t) [with _Del = std::default_delete<const std::__cxx11::basic_regex<char> >; <template-parameter-2-2> = void; _Tp = const std::__cxx11::basic_regex<char>; _Dp = std::default_delete<const std::__cxx11::basic_regex<char> >; std::nullptr_t = std::nullptr_t]’:
/data/mysql-server/fb-5.6.35/sql/handler.h:1967:22:   required from here
/usr/include/c++/10/bits/unique_ptr.h:320:9: error: no matching function for call to ‘std::__uniq_ptr_data<const std::__cxx11::basic_regex<char>, std::default_delete<const std::__cxx11::basic_regex<char> >, true, true>::__uniq_ptr_data()’
  320 |  : _M_t()
/usr/include/c++/10/bits/unique_ptr.h:209:40: note: candidate: ‘std::__uniq_ptr_data<const std::__cxx11::basic_regex<char>, std::default_delete<const std::__cxx11::basic_regex<char> >, true, true>::__uniq_ptr_data(std::__uniq_ptr_impl<const std::__cxx11::basic_regex<char>, std::default_delete<const std::__cxx11::basic_regex<char> > >::pointer) [inherited from std::__uniq_ptr_impl<const std::__cxx11::basic_regex<char>, std::default_delete<const std::__cxx11::basic_regex<char> > >]’
  209 |       using __uniq_ptr_impl<_Tp, _Dp>::__uniq_ptr_impl;
```
2.
```
In file included from /data/mysql-server/fb-5.6.35/sql/session_tracker.cc:17:
/data/mysql-server/fb-5.6.35/sql/session_tracker.h:106:44: error: ‘string’ is not a member of ‘std’
  106 |   virtual void audit_tracker(std::map<std::string, std::string>& audit_map)
```
3.
```
/data/mysql-server/fb-5.6.35/utils/perf_counters.cc: In static member function ‘static std::shared_ptr<utils::PerfCounterFactory> utils::PerfCounterFactory::getFactory(const string&)’:
/data/mysql-server/fb-5.6.35/utils/perf_counters.cc:181:20: error: no match for ‘operator==’ (operand types are ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’} and ‘const char [7]’)
  181 |   if (factory_name == "simple") {
      |       ~~~~~~~~~~~~ ^~ ~~~~~~~~
      |       |               |
      |       |               const char [7]
      |       const string {aka const std::__cxx11::basic_string<char>}
```
4.
```
/data/mysql-server/fb-5.6.35/extra/innochecksum.cc:80:33: error: ‘string’ is not a member of ‘std’
   80 | typedef std::unordered_set<std::string> TOKEN_SET_TYPE;
```
5.
```
/data/mysql-server/fb-5.6.35/include/native_procedure.h:93:46: error: ‘std::string’ has not been declared
   93 |   virtual int field_val_str(uint index, std::string *out) = 0;
```