Fix recent macOS build regression on test_bypass_rpc_plugin
Use PRIu64 to format uint64_t values to fix:

plugin/test_bypass_rpc_plugin/test_bypass_rpc_plugin_info.cc:502:28: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
  501 |         "calling bypass_select with query '%s', hlc_lower_bound_ts %lu",
      |                                                                    ~~~
      |                                                                    %llu
  502 |         query_str.c_str(), hlc_lower_bound_ts);
      |                            ^~~~~~~~~~~~~~~~~~
include/mysql/components/services/log_builtins.h:838:66: note: expanded from macro 'LogPluginErrMsg'
  838 |       .message_quoted("Plugin " LOG_COMPONENT_TAG " reported", ##__VA_ARGS__)
      |                                                                  ^~~~~~~~~~~