Fix the build break caused by deprecated declarations from latest version of RocksDB
Summary:
Currently the `{ latest MyRocks + latest RocksDB }` builds fails because `GetApproximateSizes` is marked as `ROCKSDB_DEPRECATED_FUNC`. This causes build errors like:

```
error: ‘virtual void rocksdb::DB::GetApproximateSizes(rocksdb::ColumnFamilyHandle*,
const rocksdb::Range*, int, uint64_t*, bool)’ is deprecated (declared at
.../rocksdb/include/rocksdb/db.h:629) [-Werror=deprecated-declarations]
     &sz, true);
```

This is a quick fix to unblock the integration testing.

Test Plan:
- Build MyRocks with the latest version of RocksDB from `master`.
- Observe failure.
- Apply the fix.
- Build MyRocks with the latest version of RocksDB from `master`.
- Observe succes.

Reviewers: mung, vitaliy888

Reviewed By: mung, vitaliy888

Subscribers: webscalesql-eng@

Differential Revision: https://phabricator.intern.facebook.com/D4458637

Tasks: 15624788

Signature: t1:4458637:1485300753:2d8431d0517663809ddca75cc3ba8361c88bfc45