Bug #33608154 libmysqlclient C++20 compilation fails due to reserved 'requires' keyword
Summary:
Porting upstream commits: https://github.com/mysql/mysql-server/commit/e4a4aac57279e8ce7b1e59e123f8e36f88d534f5

in C++20, requires becomes keyword and cause compiler fail

```
mysql/components/services/dynamic_loader.h:266:31: error: expected member name or ';' after declaration specifiers
  struct mysql_service_ref_t *requires;
                              ^
mysql/components/services/dynamic_loader.h:266:39: error: expected expression
  struct mysql_service_ref_t *requires;
                                      ^
mysql/components/services/dynamic_loader.h:266:31: error: trailing requires clause can only be used when declaring a function
  struct mysql_service_ref_t *requires;
```

Reviewed By: Pushapgl

Differential Revision: D38969126

fbshipit-source-id: 671ffaeb02ec04b8f9415a2195a4ea2115faf7f1