Fix mysqldump macOS build regression (#1474)
Summary:
Use the standard macro to fprintf a uint64_t value. This fixes
client/mysqldump.cc:6347:11: error: format specifies type 'unsigned long' but the argument has type 'unsigned long long' [-Werror,-Wformat]
          itr->second);
          ^~~~~~~~~~~

Squash with fb8bf5e253e8ccaf7abf9094f50ef80f74c60ae3

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1474

Differential Revision: D60674792

fbshipit-source-id: a586a132e095804e84afbd43dd6c2cf54939e7f3