use c++17 for mysqld
Summary:
rocksdb 7.0 start to use c++17 and it will cause compiler fail

```
rocksdb/include/rocksdb/slice.h:46:20: error: no type named 'string_view' in namespace 'std'
  Slice(const std::string_view& sv) : data_(sv.data()), size_(sv.size()) {}
              ~~~~~^
rocksdb/include/rocksdb/slice.h:95:8: error: no type named 'string_view' in namespace 'std'
  std::string_view ToStringView() const {
  ~~~~~^
rocksdb/include/rocksdb/slice.h:96:17: error: no member named 'string_view' in namespace 'std'
    return std::string_view(data_, size_);
```

There are two changes:
- register key isn't supported in c++17
- byte conflict with std::byte, change all mysqld byte to ::byte to avoid conflict

Reviewed By: calid

Differential Revision: D34315592

fbshipit-source-id: f2cb2735ae0aa6eab994c6296f51225f46719f98