Use PRIu64 to printf-format an uint64_t value (#1439)
Summary:
This fixes, on macOS:

```
storage/rocksdb/rdb_cmd_srv_helper.cc:115:52: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                    "expect one row, but got %lu", row_count);
                                             ~~~   ^~~~~~~~~
                                             %llu
```

At the same time add some includes for the used declarations.

Squash with 7451f04c870763ad2f5ef0bc17e18ff96865e739

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1439

Differential Revision: D55019705

fbshipit-source-id: 19a7982a62ba172714734716b08000e8762ac649