[only_mtr] Add --no-defaults to MYSQLADMIN calls
Summary:
`MYSQLADMIN` without `--no-defaults` option picks up default SSL settings that don't work for the test instances and fail with the following error:
```
mysqladmin: connect to server at 'localhost' failed
error: 'SSL connection error: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED (errno 71)'
```
Add this option to the few places that are missing it. The rest of the 94 usages are all using `--no-defaults` or specify the default settings file.

Differential Revision: D46236557