Ignoring unused-but-set-variable on unit test code
Summary:
D38265 caused release build failure because of "test_rwlocks.cc:232:7: error:
variable 'res' set but not used [-Werror=unused-but-set-variable]".
Since test_rwlocks.cc is unit test code, there is no reason to strictly follow
unused-but-set-variable rule.

Test Plan: build

Reviewers: hermanlee4, spetrunia, maykov

Reviewed By: maykov

Differential Revision: https://reviews.facebook.net/D39603