Fix GCC build regression (#1491)
Summary:
This fixes

mysys/charset.cc: In member function 'virtual int MY_CHARSET_LOADER::add_collation(CHARSET_INFO*)':
mysys/charset.cc:232:13: error: 'void* memset(void*, int, size_t)' clearing an object of type 'struct CHARSET_INFO' with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]
  232 |       memset(all_charsets[cs->number], 0, sizeof(CHARSET_INFO));
      |       ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from mysys/charset.cc:43:
include/m_ctype.h:383:8: note: 'struct CHARSET_INFO' declared here
  383 | struct CHARSET_INFO {
      |        ^~~~~~~~~~~~

Fix by removing memset and passing MY_ZEROFILL flag to the allocation function
instead.

Squash with 6637b51c7df3fb8e2c4994dd0358acb92f7ba017

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1491

Differential Revision: D63550080

fbshipit-source-id: 8b66778ddbc1569ecab885401d27c63a92f639fc