Fix build break when using 6.17.0 rocksdb
Summary:
some of run failed to build with latest rocksdb:
```
rocksdb/util/build_version.cc:1:10: fatal error: 'build_version.h' file not found
#include "build_version.h"
```

The build issue is related to rocksdb change https://github.com/facebook/rocksdb/commit/0a9a05ae12943b1529ef1eabbca5ce5a71c986bf, which removes build_version.h and also use build_version.cc.in as template to generate build_version.cc --- due to build_version.cc.in implements couple functions, We need these implements functions during link time.

The change is to mimic rocksdb change to use build_version.cc.in as template to generate build_version.cc. also rocksdb modify class StopWatchNano .cctor definition.

update-submodule: rocksdb

Reviewed By: yizhang82

Differential Revision: D26304582

fbshipit-source-id: 16594590eeb