Fix build error on std::pair comparison (#1412)
Summary:
This fixes

sql/binlog.cc:6626:52: error: invalid operands to binary expression ('std::pair<int64_t, int64_t>' (aka 'pair<long long, long long>') and 'std::pair<long, long>' (aka 'pair<long, long>'))
        if (raft_rotate_info->ingestion_checkpoint != std::pair(-1L, -1L)) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~

and

sql/binlog.cc:8809:30: error: invalid operands to binary expression ('std::pair<int64_t, int64_t>' (aka 'pair<long long, long long>') and 'std::pair<long, long>' (aka 'pair<long, long>'))
        if (param.checkpoint != std::pair(-1L, -1L)) {
            ~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~

Done in a separate commit from 2ad105fc364672361a6228238dd9523c835bf399 because of a different squash patch target.

Squash with e0c8fde56ec9777307d609a69acb5c5a92c21907

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1412

Differential Revision: D52306086

fbshipit-source-id: 3bb3b6048dd708e5a963ad6b4dfd459d0d0a901a