Use PRIu64 to printf-format an uint64_t value
This fixes, on macOS:
storage/rocksdb/rdb_cmd_srv_helper.cc:115:52: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
                    "expect one row, but got %lu", row_count);
                                             ~~~   ^~~~~~~~~
                                             %llu

At the same time add some includes for the used declarations.

Squash with 7451f04c870763ad2f5ef0bc17e18ff96865e739