Fix missing ZSTD_CLEVEL_DEFAULT
```
In file included from /data/mysql-server/fb-5.6.35/libmysqld/lib_sql.cc:30:
/data/mysql-server/fb-5.6.35/libmysqld/../sql/mysqld.cc:627:35: error: use of undeclared identifier 'ZSTD_CLEVEL_DEFAULT'
long zstd_net_compression_level = ZSTD_CLEVEL_DEFAULT;
```
```
/data/mysql-server/fb-5.6.35/sql/sys_vars.cc:3653:42: error: use of undeclared identifier 'ZSTD_CLEVEL_DEFAULT'
      VALID_RANGE(LONG_MIN, 22), DEFAULT(ZSTD_CLEVEL_DEFAULT), BLOCK_SIZE(1));
```