Fix LLVM 14 build regression under macOS
This fixes, trivially:

sql/xa/recovery.cc:234:33: error: invalid operands to binary expression ('std::pair<int64_t, int64_t>' (aka 'pair<long long, long long>') and 'pair<typename __unwrap_ref_decay<long>::type, typename __unwrap_ref_decay<long>::type>' (aka 'pair<long, long>'))
    if (info->smallest_lwm_opid == std::make_pair(-1L, -1L) ||
        ~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~

Squash with 9fc35fa64fb68b443d632e831db50ab02ac9bfce

This fixes the same class of errors as 2dc2bdd4c1b1a63b48ff61610702d0dc3a43dca1,
but the current error does not trigger with XCode clang for some reason, and is
only visible with LLVM 14 (possibly other versions too) from Homebrew.