Fix vectordb build, including macOS portability fixes (#1447)
Summary:
Fix some vectordb build issues, both general and macOS-specific:
- cmake/faiss.cmake references a non-existing BUILD_DIR CMake variable. Since it
  gets expanded to nothing, the FAISS build dir becomes /faiss, and then, if the
  root dir is unwritable:
  -- Adding faiss and its dependencies
  CMake Error at _build-debug/FAISS_EXTERNAL-prefix/tmp/FAISS_EXTERNAL-mkdirs.cmake:6 (file):
    file failed to create directory:

      /faiss

    because: Read-only file system
  Call Stack (most recent call first):
    /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/ExternalProject.cmake:1816 (include)
    /opt/homebrew/Cellar/cmake/3.29.2/share/cmake/Modules/ExternalProject.cmake:4392 (_ep_set_directories)
    cmake/faiss.cmake:14 (ExternalProject_Add)
    CMakeLists.txt:2214 (INCLUDE)
- If Ninja is used as the CMake build generator, the build fails with:
  ninja: error: 'faiss/faiss/libfaiss.a', needed by 'runtime_output_directory/mysqld', missing and no known rule to make it
  This is fixed by setting BUILD_BYPRODUCTS option on ExternalProject_Add to the
  static library name.
- Replace INCLUDE_DIRECTORIES for sql_main with more idiomatic and non-polluting
  globally TARGET_INCLUDE_DIRECTORIES
- Fix trivial macOS specific build errors on storage/rocksdb/rdb_vector_db.cc:
storage/rocksdb/rdb_vector_db.cc:90:26: error: cannot initialize a parameter of type 'uint64 *' (aka 'unsigned long long *') with an rvalue of type 'size_t *' (aka 'unsigned long *')
  if (reader.read_uint64(&actual_list_id)) {
                         ^~~~~~~~~~~~~~~
storage/rocksdb/./rdb_buff.h:325:34: note: passing argument to parameter 'res' here
  bool read_uint64(uint64 *const res) {
                                 ^
storage/rocksdb/rdb_vector_db.cc:144:63: error: format specifies type 'unsigned long' but the argument has type 'value_type' (aka 'long long') [-Werror,-Wformat]
                        "Failed to find matching pk for %lu", vector_id);
                                                        ~~~   ^~~~~~~~~
                                                        %lld
include/mysql/components/services/log_builtins.h:838:66: note: expanded from macro 'LogPluginErrMsg'
      .message_quoted("Plugin " LOG_COMPONENT_TAG " reported", ##__VA_ARGS__)
                                                                 ^~~~~~~~~~~
storage/rocksdb/rdb_vector_db.cc:145:63: error: format specifies type 'unsigned long' but the argument has type 'value_type' (aka 'long long') [-Werror,-Wformat]
                        "Failed to find matching pk for %lu", vector_id);
                                                        ~~~   ^~~~~~~~~
                                                        %lld
include/mysql/components/services/log_builtins.h:838:66: note: expanded from macro 'LogPluginErrMsg'
      .message_quoted("Plugin " LOG_COMPONENT_TAG " reported", ##__VA_ARGS__)
                                                                 ^~~~~~~~~~~

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1447

Differential Revision: D56359321

fbshipit-source-id: f227d3b8f1eb50aabf536dc7ce396294cc083f37