Pass actual format string instead of nullptr in (#1410)
Summary:
This fixes a GCC build error:

sql/sql_parse.cc:7909:17: error: too many arguments for format [-Werror=format-extra-args]
 7909 |                 static_cast<ulonglong>(thd->variables.parser_max_mem_size),

Squash with 67fcc60a43687c3e116c7f57e13b52732ad25231

Pull Request resolved: https://github.com/facebook/mysql-5.6/pull/1410

Differential Revision: D52259057

fbshipit-source-id: 164921676f5be07db3c827da71044c3be8667c13